plugins {
    id 'com.android.application'
}

android {
    namespace 'com.openworld.game'
    compileSdk 34

    defaultConfig {
        applicationId "com.openworld.game"
        minSdk 21
        targetSdk 34
        versionCode 3
        versionName "1.2"
    }

    signingConfigs {
        release {
            storeFile file("../release.keystore")
            storePassword "openworld123"
            keyAlias "openworld"
            keyPassword "openworld123"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    lint {
        checkReleaseBuilds false
    }
}